site_name: "CodeHive - Project Docs"
site_url: https://CodeHive-QA.github.com/project-docs
site_description: "Documentation for our team projects"
theme:
  name: readthedocs

repo_url: https://github.com/CodeHive-QA/project-docs/
edit_uri: edit/main/docs/

nav:
  - Home: index.md
  - Minecraft: minecraft.md
